2018-04-08 12:21:37 Backend\Exception\CustomException: 签名错误 in E:\project\backend\backend\behavior\VerifySign.php:40
Stack trace:
#0 [internal function]: Backend\behavior\VerifySign->verifySignature()
#1 E:\project\backend\vendor\yiisoft\yii2\base\Component.php(297): call_user_func_array(Array, Array)
#2 E:\project\backend\backend\modules\common\controllers\BusinessController.php(77): yii\base\Component->__call('verifySignature', Array)
#3 E:\project\backend\vendor\yiisoft\yii2\base\Controller.php(155): Backend\modules\common\controllers\BusinessController->beforeAction(Object(yii\rest\UpdateAction))
#4 E:\project\backend\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('update', Array)
#5 E:\project\backend\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('admin/admin-use...', Array)
#6 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#7 E:\project\backend\public\index.php(20): yii\base\Application->run()
#8 {main}
2018-04-08 12:23:36 Backend\Exception\CustomException: 签名错误 in E:\project\backend\backend\behavior\VerifySign.php:40
Stack trace:
#0 [internal function]: Backend\behavior\VerifySign->verifySignature()
#1 E:\project\backend\vendor\yiisoft\yii2\base\Component.php(297): call_user_func_array(Array, Array)
#2 E:\project\backend\backend\modules\common\controllers\BusinessController.php(77): yii\base\Component->__call('verifySignature', Array)
#3 E:\project\backend\vendor\yiisoft\yii2\base\Controller.php(155): Backend\modules\common\controllers\BusinessController->beforeAction(Object(yii\rest\UpdateAction))
#4 E:\project\backend\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('update', Array)
#5 E:\project\backend\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('admin/admin-use...', Array)
#6 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#7 E:\project\backend\public\index.php(20): yii\base\Application->run()
#8 {main}
2018-04-08 12:49:41 Backend\Exception\CustomException: 签名错误 in E:\project\backend\backend\behavior\VerifySign.php:40
Stack trace:
#0 [internal function]: Backend\behavior\VerifySign->verifySignature()
#1 E:\project\backend\vendor\yiisoft\yii2\base\Component.php(297): call_user_func_array(Array, Array)
#2 E:\project\backend\backend\modules\common\controllers\BusinessController.php(77): yii\base\Component->__call('verifySignature', Array)
#3 E:\project\backend\vendor\yiisoft\yii2\base\Controller.php(155): Backend\modules\common\controllers\BusinessController->beforeAction(Object(yii\rest\UpdateAction))
#4 E:\project\backend\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('update', Array)
#5 E:\project\backend\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('admin/admin-use...', Array)
#6 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#7 E:\project\backend\public\index.php(20): yii\base\Application->run()
#8 {main}
